version: 1.2
workflows:
 - name: Apollo_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_apollo_pe.wdl
   testParameterFiles:
    - empty.json
 - name: kSNP3
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ksnp3.wdl
   testParameterFiles:
    - empty.json
 - name: Apollo_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_apollo_illumina_pe.wdl
   testParameterFiles:
    - empty.json
