version: 1.2
workflows:
 - name: kSNP3
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ksnp3.wdl
   testParameterFiles:
    - empty.json
 - name: Gambit_Query
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_gambit_query.wdl
   testParameterFiles:
    - empty.json
 - name: Kleborate
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_kleborate.wdl
   testParameterFiles:
    - empty.json
 - name: SerotypeFinder
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_serotypefinder.wdl
   testParameterFiles:
    - empty.json
 - name: TBProfiler_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_tbprofiler_pe.wdl
   testParameterFiles:
    - empty.json
 - name: TBProfiler_ONT
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_tbprofiler_ont.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaProk_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_theiaprok_illumina_pe.wdl
   testParameterFiles:
    - empty.json
 - name: MashTree_FASTA
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mashtree_fasta.wdl
   testParameterFiles:
    - empty.json
 - name: Kraken2_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_kraken2_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Kraken2_SE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_kraken2_se.wdl
   testParameterFiles:
    - empty.json
